/********************************************************************************
** Form generated from reading UI file 'RGBSegment.ui'
**
** Created: Wed 24. Oct 14:56:48 2012
**      by: Qt User Interface Compiler version 4.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_RGBSEGMENT_H
#define UI_RGBSEGMENT_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QGridLayout>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>
#include <QtGui/QStackedWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_RGBSegment
{
public:
    QGridLayout *gridLayout_2;
    QComboBox *comboBox;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QWidget *layoutWidget;
    QGridLayout *gridLayout;
    QLabel *label;
    QSpinBox *sbx;
    QLabel *lcolorx;
    QPushButton *pbColorDialogx;
    QLabel *label_2;
    QSpinBox *sby;
    QLabel *lcolory;
    QPushButton *pbColorDialogy;
    QWidget *page_2;
    QGroupBox *groupBox;
    QLabel *label_3;
    QSpinBox *sbxa2;
    QLabel *label_4;
    QSpinBox *sbya2;
    QLabel *lcolora2;
    QLabel *lcolorb2;
    QPushButton *pbColorDialogxa;
    QPushButton *pbColorDialogya;
    QGroupBox *groupBox_2;
    QLabel *label_7;
    QSpinBox *sbxb2;
    QLabel *lcolorc2;
    QPushButton *pbColorDialogxb;
    QLabel *label_8;
    QSpinBox *sbyb2;
    QLabel *lcolord2;
    QPushButton *pbColorDialogyb;
    QWidget *page_3;
    QGroupBox *groupBox_3;
    QLabel *label_5;
    QLabel *label_6;
    QSpinBox *sbxa3;
    QSpinBox *sbya3;
    QLabel *lcolora3;
    QLabel *lcolorb3;
    QPushButton *pbColorDialoga3;
    QPushButton *pbColorDialogb3;
    QGroupBox *groupBox_4;
    QLabel *label_11;
    QLabel *label_12;
    QSpinBox *sbxb3;
    QSpinBox *sbyb3;
    QLabel *lcolorc3;
    QLabel *lcolord3;
    QPushButton *pbColorDialogc3;
    QPushButton *pbColorDialogd3;
    QGroupBox *groupBox_5;
    QLabel *label_15;
    QLabel *label_16;
    QSpinBox *sbxc3;
    QSpinBox *sbyc3;
    QLabel *lcolore3;
    QLabel *lcolorf3;
    QPushButton *pbColorDialoge3;
    QPushButton *pbColorDialogf3;
    QWidget *page_4;
    QGroupBox *groupBox_6;
    QLabel *label_9;
    QLabel *label_10;
    QSpinBox *sbxa4;
    QSpinBox *sbya4;
    QLabel *lcolora4;
    QLabel *lcolorb4;
    QPushButton *pbColorDialoga4;
    QPushButton *pbColorDialogb4;
    QGroupBox *groupBox_7;
    QLabel *label_17;
    QLabel *label_18;
    QSpinBox *sbxb4;
    QSpinBox *sbyb4;
    QLabel *lcolorc4;
    QLabel *lcolord4;
    QPushButton *pbColorDialogc4;
    QPushButton *pbColorDialogd4;
    QGroupBox *groupBox_8;
    QLabel *label_21;
    QLabel *label_22;
    QSpinBox *sbxc4;
    QSpinBox *sbyc4;
    QLabel *lcolore4;
    QLabel *lcolorf4;
    QPushButton *pbColorDialoge4;
    QPushButton *pbColorDialogf4;
    QGroupBox *groupBox_9;
    QLabel *label_25;
    QLabel *label_26;
    QSpinBox *sbxd4;
    QSpinBox *sbyd4;
    QLabel *lcolorg4;
    QLabel *lcolorh4;
    QPushButton *pbColorDialogg4;
    QPushButton *pbColorDialogh4;
    QWidget *page_5;
    QGroupBox *groupBox_10;
    QLabel *label_13;
    QLabel *label_14;
    QSpinBox *sbxa5;
    QSpinBox *sbya5;
    QLabel *lcolora5;
    QLabel *lcolorb5;
    QPushButton *pbColorDialoga5;
    QPushButton *pbColorDialogb5;
    QGroupBox *groupBox_11;
    QLabel *label_19;
    QLabel *label_20;
    QSpinBox *sbxb5;
    QSpinBox *sbyb5;
    QLabel *lcolorc5;
    QLabel *lcolord5;
    QPushButton *pbColorDialogc5;
    QPushButton *pbColorDialogd5;
    QGroupBox *groupBox_12;
    QLabel *label_23;
    QLabel *label_24;
    QSpinBox *sbxc5;
    QSpinBox *sbyc5;
    QLabel *lcolore5;
    QLabel *lcolorf5;
    QPushButton *pbColorDialoge5;
    QPushButton *pbColorDialogf5;
    QGroupBox *groupBox_13;
    QLabel *label_27;
    QLabel *label_28;
    QSpinBox *sbxd5;
    QSpinBox *sbyd5;
    QLabel *lcolorg5;
    QLabel *lcolorh5;
    QPushButton *pbColorDialogg5;
    QPushButton *pbColorDialogh5;
    QGroupBox *groupBox_14;
    QLabel *label_29;
    QLabel *label_30;
    QSpinBox *sbxe5;
    QSpinBox *sbye5;
    QLabel *lcolori5;
    QLabel *lcolorj5;
    QPushButton *pbColorDialogi5;
    QPushButton *pbColorDialogj5;
    QWidget *page_6;
    QGroupBox *groupBox_15;
    QLabel *label_31;
    QLabel *label_32;
    QSpinBox *sbxb6;
    QSpinBox *sbyb6;
    QLabel *lcolorc6;
    QLabel *lcolord6;
    QPushButton *pbColorDialogc6;
    QPushButton *pbColorDialogd6;
    QGroupBox *groupBox_16;
    QLabel *label_33;
    QLabel *label_34;
    QSpinBox *sbxa6;
    QSpinBox *sbya6;
    QLabel *lcolora6;
    QLabel *lcolorb6;
    QPushButton *pbColorDialoga6;
    QPushButton *pbColorDialogb6;
    QGroupBox *groupBox_17;
    QLabel *label_35;
    QLabel *label_36;
    QSpinBox *sbxd6;
    QSpinBox *sbyd6;
    QLabel *lcolorg6;
    QLabel *lcolorh6;
    QPushButton *pbColorDialogg6;
    QPushButton *pbColorDialogh6;
    QGroupBox *groupBox_18;
    QLabel *label_37;
    QLabel *label_38;
    QSpinBox *sbxe6;
    QSpinBox *sbye6;
    QLabel *lcolori6;
    QLabel *lcolorj6;
    QPushButton *pbColorDialogi6;
    QPushButton *pbColorDialogj6;
    QGroupBox *groupBox_19;
    QLabel *label_39;
    QLabel *label_40;
    QSpinBox *sbxc6;
    QSpinBox *sbyc6;
    QLabel *lcolore6;
    QLabel *lcolorf6;
    QPushButton *pbColorDialoge6;
    QPushButton *pbColorDialogf6;
    QGroupBox *groupBox_20;
    QLabel *label_41;
    QLabel *label_42;
    QSpinBox *sbxf6;
    QSpinBox *sbyf6;
    QLabel *lcolork6;
    QLabel *lcolorl6;
    QPushButton *pbColorDialogk6;
    QPushButton *pbColorDialogl6;
    QWidget *page_7;
    QGroupBox *groupBox_21;
    QLabel *label_43;
    QLabel *label_44;
    QSpinBox *sbxa7;
    QSpinBox *sbya7;
    QLabel *lcolora7;
    QLabel *lcolorb7;
    QPushButton *pbColorDialoga7;
    QPushButton *pbColorDialogb7;
    QGroupBox *groupBox_22;
    QLabel *label_45;
    QLabel *label_46;
    QSpinBox *sbxb7;
    QSpinBox *sbyb7;
    QLabel *lcolorc7;
    QLabel *lcolord7;
    QPushButton *pbColorDialogc7;
    QPushButton *pbColorDialogd7;
    QGroupBox *groupBox_23;
    QLabel *label_47;
    QLabel *label_48;
    QSpinBox *sbxd7;
    QSpinBox *sbyd7;
    QLabel *lcolorg7;
    QLabel *lcolorh7;
    QPushButton *pbColorDialogg7;
    QPushButton *pbColorDialogh7;
    QGroupBox *groupBox_24;
    QLabel *label_49;
    QLabel *label_50;
    QSpinBox *sbxe7;
    QSpinBox *sbye7;
    QLabel *lcolori7;
    QLabel *lcolorj7;
    QPushButton *pbColorDialogi7;
    QPushButton *pbColorDialogj7;
    QGroupBox *groupBox_25;
    QLabel *label_51;
    QLabel *label_52;
    QSpinBox *sbxc7;
    QSpinBox *sbyc7;
    QLabel *lcolore7;
    QLabel *lcolorf7;
    QPushButton *pbColorDialoge7;
    QPushButton *pbColorDialogf7;
    QGroupBox *groupBox_26;
    QLabel *label_53;
    QLabel *label_54;
    QSpinBox *sbxf7;
    QSpinBox *sbyf7;
    QLabel *lcolork7;
    QLabel *lcolorl7;
    QPushButton *pbColorDialogk7;
    QPushButton *pbColorDialogl7;
    QGroupBox *groupBox_27;
    QLabel *label_55;
    QLabel *label_56;
    QSpinBox *sbxg7;
    QSpinBox *sbyg7;
    QLabel *lcolorm7;
    QLabel *lcolorn7;
    QPushButton *pbColorDialogm7;
    QPushButton *pbColorDialogn7;
    QPushButton *pbCancel;
    QPushButton *pbAccept;

    void setupUi(QWidget *RGBSegment)
    {
        if (RGBSegment->objectName().isEmpty())
            RGBSegment->setObjectName(QString::fromUtf8("RGBSegment"));
        RGBSegment->resize(586, 505);
        gridLayout_2 = new QGridLayout(RGBSegment);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        comboBox = new QComboBox(RGBSegment);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));

        gridLayout_2->addWidget(comboBox, 0, 0, 1, 3);

        stackedWidget = new QStackedWidget(RGBSegment);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        layoutWidget = new QWidget(page);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(10, 50, 261, 61));
        gridLayout = new QGridLayout(layoutWidget);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setContentsMargins(0, 0, 0, 0);
        label = new QLabel(layoutWidget);
        label->setObjectName(QString::fromUtf8("label"));
        QFont font;
        font.setPointSize(13);
        label->setFont(font);

        gridLayout->addWidget(label, 0, 0, 2, 2);

        sbx = new QSpinBox(layoutWidget);
        sbx->setObjectName(QString::fromUtf8("sbx"));
        sbx->setMaximum(4096);

        gridLayout->addWidget(sbx, 1, 1, 1, 1);

        lcolorx = new QLabel(layoutWidget);
        lcolorx->setObjectName(QString::fromUtf8("lcolorx"));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        lcolorx->setPalette(palette);
        lcolorx->setFont(font);

        gridLayout->addWidget(lcolorx, 1, 2, 1, 1);

        pbColorDialogx = new QPushButton(layoutWidget);
        pbColorDialogx->setObjectName(QString::fromUtf8("pbColorDialogx"));

        gridLayout->addWidget(pbColorDialogx, 1, 3, 1, 1);

        label_2 = new QLabel(layoutWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setFont(font);

        gridLayout->addWidget(label_2, 2, 0, 1, 1);

        sby = new QSpinBox(layoutWidget);
        sby->setObjectName(QString::fromUtf8("sby"));
        sby->setMaximum(4096);

        gridLayout->addWidget(sby, 2, 1, 1, 1);

        lcolory = new QLabel(layoutWidget);
        lcolory->setObjectName(QString::fromUtf8("lcolory"));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lcolory->setPalette(palette1);
        lcolory->setFont(font);

        gridLayout->addWidget(lcolory, 2, 2, 1, 1);

        pbColorDialogy = new QPushButton(layoutWidget);
        pbColorDialogy->setObjectName(QString::fromUtf8("pbColorDialogy"));

        gridLayout->addWidget(pbColorDialogy, 2, 3, 1, 1);

        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        groupBox = new QGroupBox(page_2);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(20, 20, 251, 101));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 20, 60, 21));
        sbxa2 = new QSpinBox(groupBox);
        sbxa2->setObjectName(QString::fromUtf8("sbxa2"));
        sbxa2->setGeometry(QRect(70, 20, 42, 22));
        sbxa2->setMaximum(4096);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 70, 51, 16));
        sbya2 = new QSpinBox(groupBox);
        sbya2->setObjectName(QString::fromUtf8("sbya2"));
        sbya2->setGeometry(QRect(70, 70, 42, 22));
        sbya2->setMaximum(4096);
        lcolora2 = new QLabel(groupBox);
        lcolora2->setObjectName(QString::fromUtf8("lcolora2"));
        lcolora2->setGeometry(QRect(120, 20, 21, 21));
        lcolorb2 = new QLabel(groupBox);
        lcolorb2->setObjectName(QString::fromUtf8("lcolorb2"));
        lcolorb2->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogxa = new QPushButton(groupBox);
        pbColorDialogxa->setObjectName(QString::fromUtf8("pbColorDialogxa"));
        pbColorDialogxa->setGeometry(QRect(150, 20, 91, 23));
        pbColorDialogya = new QPushButton(groupBox);
        pbColorDialogya->setObjectName(QString::fromUtf8("pbColorDialogya"));
        pbColorDialogya->setGeometry(QRect(150, 70, 91, 23));
        groupBox_2 = new QGroupBox(page_2);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(20, 160, 251, 101));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(6, 20, 61, 21));
        sbxb2 = new QSpinBox(groupBox_2);
        sbxb2->setObjectName(QString::fromUtf8("sbxb2"));
        sbxb2->setGeometry(QRect(66, 20, 42, 22));
        sbxb2->setMaximum(4096);
        lcolorc2 = new QLabel(groupBox_2);
        lcolorc2->setObjectName(QString::fromUtf8("lcolorc2"));
        lcolorc2->setGeometry(QRect(120, 20, 21, 21));
        pbColorDialogxb = new QPushButton(groupBox_2);
        pbColorDialogxb->setObjectName(QString::fromUtf8("pbColorDialogxb"));
        pbColorDialogxb->setGeometry(QRect(150, 20, 91, 23));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(6, 70, 51, 21));
        sbyb2 = new QSpinBox(groupBox_2);
        sbyb2->setObjectName(QString::fromUtf8("sbyb2"));
        sbyb2->setGeometry(QRect(66, 70, 42, 22));
        sbyb2->setMaximum(4096);
        lcolord2 = new QLabel(groupBox_2);
        lcolord2->setObjectName(QString::fromUtf8("lcolord2"));
        lcolord2->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogyb = new QPushButton(groupBox_2);
        pbColorDialogyb->setObjectName(QString::fromUtf8("pbColorDialogyb"));
        pbColorDialogyb->setGeometry(QRect(150, 70, 91, 23));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        groupBox_3 = new QGroupBox(page_3);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(20, 10, 251, 101));
        label_5 = new QLabel(groupBox_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 20, 61, 21));
        label_6 = new QLabel(groupBox_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 60, 51, 21));
        sbxa3 = new QSpinBox(groupBox_3);
        sbxa3->setObjectName(QString::fromUtf8("sbxa3"));
        sbxa3->setGeometry(QRect(70, 20, 42, 22));
        sbxa3->setMaximum(4096);
        sbya3 = new QSpinBox(groupBox_3);
        sbya3->setObjectName(QString::fromUtf8("sbya3"));
        sbya3->setGeometry(QRect(70, 60, 42, 22));
        sbya3->setMaximum(4096);
        lcolora3 = new QLabel(groupBox_3);
        lcolora3->setObjectName(QString::fromUtf8("lcolora3"));
        lcolora3->setGeometry(QRect(120, 20, 21, 21));
        lcolorb3 = new QLabel(groupBox_3);
        lcolorb3->setObjectName(QString::fromUtf8("lcolorb3"));
        lcolorb3->setGeometry(QRect(120, 60, 21, 21));
        pbColorDialoga3 = new QPushButton(groupBox_3);
        pbColorDialoga3->setObjectName(QString::fromUtf8("pbColorDialoga3"));
        pbColorDialoga3->setGeometry(QRect(154, 20, 91, 23));
        pbColorDialogb3 = new QPushButton(groupBox_3);
        pbColorDialogb3->setObjectName(QString::fromUtf8("pbColorDialogb3"));
        pbColorDialogb3->setGeometry(QRect(154, 60, 91, 23));
        groupBox_4 = new QGroupBox(page_3);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(270, 150, 251, 101));
        label_11 = new QLabel(groupBox_4);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 30, 61, 21));
        label_12 = new QLabel(groupBox_4);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 70, 51, 21));
        sbxb3 = new QSpinBox(groupBox_4);
        sbxb3->setObjectName(QString::fromUtf8("sbxb3"));
        sbxb3->setGeometry(QRect(70, 30, 42, 22));
        sbxb3->setMaximum(4096);
        sbyb3 = new QSpinBox(groupBox_4);
        sbyb3->setObjectName(QString::fromUtf8("sbyb3"));
        sbyb3->setGeometry(QRect(70, 70, 42, 22));
        sbyb3->setMaximum(4096);
        lcolorc3 = new QLabel(groupBox_4);
        lcolorc3->setObjectName(QString::fromUtf8("lcolorc3"));
        lcolorc3->setGeometry(QRect(120, 30, 21, 21));
        lcolord3 = new QLabel(groupBox_4);
        lcolord3->setObjectName(QString::fromUtf8("lcolord3"));
        lcolord3->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogc3 = new QPushButton(groupBox_4);
        pbColorDialogc3->setObjectName(QString::fromUtf8("pbColorDialogc3"));
        pbColorDialogc3->setGeometry(QRect(150, 30, 91, 23));
        pbColorDialogd3 = new QPushButton(groupBox_4);
        pbColorDialogd3->setObjectName(QString::fromUtf8("pbColorDialogd3"));
        pbColorDialogd3->setGeometry(QRect(150, 70, 91, 23));
        groupBox_5 = new QGroupBox(page_3);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(20, 270, 251, 101));
        label_15 = new QLabel(groupBox_5);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 20, 61, 21));
        label_16 = new QLabel(groupBox_5);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 60, 61, 21));
        sbxc3 = new QSpinBox(groupBox_5);
        sbxc3->setObjectName(QString::fromUtf8("sbxc3"));
        sbxc3->setGeometry(QRect(70, 20, 42, 22));
        sbxc3->setMaximum(4096);
        sbyc3 = new QSpinBox(groupBox_5);
        sbyc3->setObjectName(QString::fromUtf8("sbyc3"));
        sbyc3->setGeometry(QRect(70, 60, 42, 22));
        sbyc3->setMaximum(4096);
        lcolore3 = new QLabel(groupBox_5);
        lcolore3->setObjectName(QString::fromUtf8("lcolore3"));
        lcolore3->setGeometry(QRect(120, 22, 21, 21));
        lcolorf3 = new QLabel(groupBox_5);
        lcolorf3->setObjectName(QString::fromUtf8("lcolorf3"));
        lcolorf3->setGeometry(QRect(120, 60, 21, 21));
        pbColorDialoge3 = new QPushButton(groupBox_5);
        pbColorDialoge3->setObjectName(QString::fromUtf8("pbColorDialoge3"));
        pbColorDialoge3->setGeometry(QRect(150, 20, 91, 23));
        pbColorDialogf3 = new QPushButton(groupBox_5);
        pbColorDialogf3->setObjectName(QString::fromUtf8("pbColorDialogf3"));
        pbColorDialogf3->setGeometry(QRect(150, 60, 91, 23));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        groupBox_6 = new QGroupBox(page_4);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 40, 251, 101));
        label_9 = new QLabel(groupBox_6);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 30, 61, 21));
        label_10 = new QLabel(groupBox_6);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 70, 51, 21));
        sbxa4 = new QSpinBox(groupBox_6);
        sbxa4->setObjectName(QString::fromUtf8("sbxa4"));
        sbxa4->setGeometry(QRect(70, 30, 42, 22));
        sbxa4->setMaximum(4096);
        sbya4 = new QSpinBox(groupBox_6);
        sbya4->setObjectName(QString::fromUtf8("sbya4"));
        sbya4->setGeometry(QRect(70, 70, 42, 22));
        sbya4->setMaximum(4096);
        lcolora4 = new QLabel(groupBox_6);
        lcolora4->setObjectName(QString::fromUtf8("lcolora4"));
        lcolora4->setGeometry(QRect(120, 30, 21, 21));
        lcolorb4 = new QLabel(groupBox_6);
        lcolorb4->setObjectName(QString::fromUtf8("lcolorb4"));
        lcolorb4->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoga4 = new QPushButton(groupBox_6);
        pbColorDialoga4->setObjectName(QString::fromUtf8("pbColorDialoga4"));
        pbColorDialoga4->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogb4 = new QPushButton(groupBox_6);
        pbColorDialogb4->setObjectName(QString::fromUtf8("pbColorDialogb4"));
        pbColorDialogb4->setGeometry(QRect(154, 70, 91, 23));
        groupBox_7 = new QGroupBox(page_4);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(270, 40, 251, 101));
        label_17 = new QLabel(groupBox_7);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 30, 46, 13));
        label_18 = new QLabel(groupBox_7);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 70, 46, 13));
        sbxb4 = new QSpinBox(groupBox_7);
        sbxb4->setObjectName(QString::fromUtf8("sbxb4"));
        sbxb4->setGeometry(QRect(60, 30, 42, 22));
        sbxb4->setMaximum(4096);
        sbyb4 = new QSpinBox(groupBox_7);
        sbyb4->setObjectName(QString::fromUtf8("sbyb4"));
        sbyb4->setGeometry(QRect(60, 70, 42, 22));
        sbyb4->setMaximum(4096);
        lcolorc4 = new QLabel(groupBox_7);
        lcolorc4->setObjectName(QString::fromUtf8("lcolorc4"));
        lcolorc4->setGeometry(QRect(110, 30, 21, 21));
        lcolord4 = new QLabel(groupBox_7);
        lcolord4->setObjectName(QString::fromUtf8("lcolord4"));
        lcolord4->setGeometry(QRect(110, 70, 21, 21));
        pbColorDialogc4 = new QPushButton(groupBox_7);
        pbColorDialogc4->setObjectName(QString::fromUtf8("pbColorDialogc4"));
        pbColorDialogc4->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogd4 = new QPushButton(groupBox_7);
        pbColorDialogd4->setObjectName(QString::fromUtf8("pbColorDialogd4"));
        pbColorDialogd4->setGeometry(QRect(154, 70, 91, 23));
        groupBox_8 = new QGroupBox(page_4);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(10, 190, 251, 101));
        label_21 = new QLabel(groupBox_8);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(5, 30, 61, 21));
        label_22 = new QLabel(groupBox_8);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(15, 70, 51, 21));
        sbxc4 = new QSpinBox(groupBox_8);
        sbxc4->setObjectName(QString::fromUtf8("sbxc4"));
        sbxc4->setGeometry(QRect(70, 30, 42, 22));
        sbxc4->setMaximum(4096);
        sbyc4 = new QSpinBox(groupBox_8);
        sbyc4->setObjectName(QString::fromUtf8("sbyc4"));
        sbyc4->setGeometry(QRect(70, 70, 42, 22));
        sbyc4->setMinimum(0);
        sbyc4->setMaximum(4096);
        lcolore4 = new QLabel(groupBox_8);
        lcolore4->setObjectName(QString::fromUtf8("lcolore4"));
        lcolore4->setGeometry(QRect(120, 30, 21, 21));
        lcolorf4 = new QLabel(groupBox_8);
        lcolorf4->setObjectName(QString::fromUtf8("lcolorf4"));
        lcolorf4->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoge4 = new QPushButton(groupBox_8);
        pbColorDialoge4->setObjectName(QString::fromUtf8("pbColorDialoge4"));
        pbColorDialoge4->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogf4 = new QPushButton(groupBox_8);
        pbColorDialogf4->setObjectName(QString::fromUtf8("pbColorDialogf4"));
        pbColorDialogf4->setGeometry(QRect(154, 70, 91, 23));
        groupBox_9 = new QGroupBox(page_4);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(270, 190, 251, 101));
        label_25 = new QLabel(groupBox_9);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 30, 61, 21));
        label_26 = new QLabel(groupBox_9);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 70, 61, 21));
        sbxd4 = new QSpinBox(groupBox_9);
        sbxd4->setObjectName(QString::fromUtf8("sbxd4"));
        sbxd4->setGeometry(QRect(70, 30, 42, 22));
        sbxd4->setMaximum(4096);
        sbyd4 = new QSpinBox(groupBox_9);
        sbyd4->setObjectName(QString::fromUtf8("sbyd4"));
        sbyd4->setGeometry(QRect(70, 70, 42, 22));
        sbyd4->setMaximum(4096);
        lcolorg4 = new QLabel(groupBox_9);
        lcolorg4->setObjectName(QString::fromUtf8("lcolorg4"));
        lcolorg4->setGeometry(QRect(120, 30, 21, 21));
        lcolorh4 = new QLabel(groupBox_9);
        lcolorh4->setObjectName(QString::fromUtf8("lcolorh4"));
        lcolorh4->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogg4 = new QPushButton(groupBox_9);
        pbColorDialogg4->setObjectName(QString::fromUtf8("pbColorDialogg4"));
        pbColorDialogg4->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogh4 = new QPushButton(groupBox_9);
        pbColorDialogh4->setObjectName(QString::fromUtf8("pbColorDialogh4"));
        pbColorDialogh4->setGeometry(QRect(154, 70, 91, 23));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        groupBox_10 = new QGroupBox(page_5);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(20, 30, 251, 101));
        label_13 = new QLabel(groupBox_10);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 30, 61, 21));
        label_14 = new QLabel(groupBox_10);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 70, 51, 16));
        sbxa5 = new QSpinBox(groupBox_10);
        sbxa5->setObjectName(QString::fromUtf8("sbxa5"));
        sbxa5->setGeometry(QRect(70, 30, 42, 22));
        sbxa5->setMaximum(4096);
        sbya5 = new QSpinBox(groupBox_10);
        sbya5->setObjectName(QString::fromUtf8("sbya5"));
        sbya5->setGeometry(QRect(70, 70, 42, 22));
        sbya5->setMaximum(4096);
        lcolora5 = new QLabel(groupBox_10);
        lcolora5->setObjectName(QString::fromUtf8("lcolora5"));
        lcolora5->setGeometry(QRect(120, 30, 21, 21));
        lcolorb5 = new QLabel(groupBox_10);
        lcolorb5->setObjectName(QString::fromUtf8("lcolorb5"));
        lcolorb5->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoga5 = new QPushButton(groupBox_10);
        pbColorDialoga5->setObjectName(QString::fromUtf8("pbColorDialoga5"));
        pbColorDialoga5->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogb5 = new QPushButton(groupBox_10);
        pbColorDialogb5->setObjectName(QString::fromUtf8("pbColorDialogb5"));
        pbColorDialogb5->setGeometry(QRect(154, 70, 91, 23));
        groupBox_11 = new QGroupBox(page_5);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(280, 30, 251, 101));
        label_19 = new QLabel(groupBox_11);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 30, 61, 21));
        label_20 = new QLabel(groupBox_11);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 70, 51, 21));
        sbxb5 = new QSpinBox(groupBox_11);
        sbxb5->setObjectName(QString::fromUtf8("sbxb5"));
        sbxb5->setGeometry(QRect(70, 30, 42, 22));
        sbxb5->setMaximum(4096);
        sbyb5 = new QSpinBox(groupBox_11);
        sbyb5->setObjectName(QString::fromUtf8("sbyb5"));
        sbyb5->setGeometry(QRect(70, 70, 42, 22));
        sbyb5->setMaximum(4096);
        lcolorc5 = new QLabel(groupBox_11);
        lcolorc5->setObjectName(QString::fromUtf8("lcolorc5"));
        lcolorc5->setGeometry(QRect(120, 30, 21, 21));
        lcolord5 = new QLabel(groupBox_11);
        lcolord5->setObjectName(QString::fromUtf8("lcolord5"));
        lcolord5->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogc5 = new QPushButton(groupBox_11);
        pbColorDialogc5->setObjectName(QString::fromUtf8("pbColorDialogc5"));
        pbColorDialogc5->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogd5 = new QPushButton(groupBox_11);
        pbColorDialogd5->setObjectName(QString::fromUtf8("pbColorDialogd5"));
        pbColorDialogd5->setGeometry(QRect(154, 70, 91, 23));
        groupBox_12 = new QGroupBox(page_5);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(20, 150, 251, 101));
        label_23 = new QLabel(groupBox_12);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 30, 61, 21));
        label_24 = new QLabel(groupBox_12);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 70, 61, 16));
        sbxc5 = new QSpinBox(groupBox_12);
        sbxc5->setObjectName(QString::fromUtf8("sbxc5"));
        sbxc5->setGeometry(QRect(70, 30, 42, 22));
        sbxc5->setMaximum(4096);
        sbyc5 = new QSpinBox(groupBox_12);
        sbyc5->setObjectName(QString::fromUtf8("sbyc5"));
        sbyc5->setGeometry(QRect(70, 70, 42, 22));
        sbyc5->setMaximum(4096);
        lcolore5 = new QLabel(groupBox_12);
        lcolore5->setObjectName(QString::fromUtf8("lcolore5"));
        lcolore5->setGeometry(QRect(120, 30, 21, 21));
        lcolorf5 = new QLabel(groupBox_12);
        lcolorf5->setObjectName(QString::fromUtf8("lcolorf5"));
        lcolorf5->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoge5 = new QPushButton(groupBox_12);
        pbColorDialoge5->setObjectName(QString::fromUtf8("pbColorDialoge5"));
        pbColorDialoge5->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogf5 = new QPushButton(groupBox_12);
        pbColorDialogf5->setObjectName(QString::fromUtf8("pbColorDialogf5"));
        pbColorDialogf5->setGeometry(QRect(154, 70, 91, 23));
        groupBox_13 = new QGroupBox(page_5);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(280, 150, 251, 101));
        label_27 = new QLabel(groupBox_13);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 30, 61, 21));
        label_28 = new QLabel(groupBox_13);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 70, 51, 21));
        sbxd5 = new QSpinBox(groupBox_13);
        sbxd5->setObjectName(QString::fromUtf8("sbxd5"));
        sbxd5->setGeometry(QRect(70, 30, 42, 22));
        sbxd5->setMaximum(4096);
        sbyd5 = new QSpinBox(groupBox_13);
        sbyd5->setObjectName(QString::fromUtf8("sbyd5"));
        sbyd5->setGeometry(QRect(70, 70, 42, 22));
        sbyd5->setMaximum(4096);
        lcolorg5 = new QLabel(groupBox_13);
        lcolorg5->setObjectName(QString::fromUtf8("lcolorg5"));
        lcolorg5->setGeometry(QRect(120, 30, 21, 21));
        lcolorh5 = new QLabel(groupBox_13);
        lcolorh5->setObjectName(QString::fromUtf8("lcolorh5"));
        lcolorh5->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogg5 = new QPushButton(groupBox_13);
        pbColorDialogg5->setObjectName(QString::fromUtf8("pbColorDialogg5"));
        pbColorDialogg5->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogh5 = new QPushButton(groupBox_13);
        pbColorDialogh5->setObjectName(QString::fromUtf8("pbColorDialogh5"));
        pbColorDialogh5->setGeometry(QRect(154, 70, 91, 23));
        groupBox_14 = new QGroupBox(page_5);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(160, 270, 251, 101));
        label_29 = new QLabel(groupBox_14);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 30, 61, 16));
        label_30 = new QLabel(groupBox_14);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 70, 51, 16));
        sbxe5 = new QSpinBox(groupBox_14);
        sbxe5->setObjectName(QString::fromUtf8("sbxe5"));
        sbxe5->setGeometry(QRect(70, 30, 42, 22));
        sbxe5->setMaximum(4096);
        sbye5 = new QSpinBox(groupBox_14);
        sbye5->setObjectName(QString::fromUtf8("sbye5"));
        sbye5->setGeometry(QRect(70, 70, 42, 22));
        sbye5->setMaximum(4096);
        lcolori5 = new QLabel(groupBox_14);
        lcolori5->setObjectName(QString::fromUtf8("lcolori5"));
        lcolori5->setGeometry(QRect(120, 30, 21, 21));
        lcolorj5 = new QLabel(groupBox_14);
        lcolorj5->setObjectName(QString::fromUtf8("lcolorj5"));
        lcolorj5->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogi5 = new QPushButton(groupBox_14);
        pbColorDialogi5->setObjectName(QString::fromUtf8("pbColorDialogi5"));
        pbColorDialogi5->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogj5 = new QPushButton(groupBox_14);
        pbColorDialogj5->setObjectName(QString::fromUtf8("pbColorDialogj5"));
        pbColorDialogj5->setGeometry(QRect(154, 70, 91, 23));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        groupBox_15 = new QGroupBox(page_6);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(280, 10, 251, 101));
        label_31 = new QLabel(groupBox_15);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 30, 61, 21));
        label_32 = new QLabel(groupBox_15);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 70, 51, 21));
        sbxb6 = new QSpinBox(groupBox_15);
        sbxb6->setObjectName(QString::fromUtf8("sbxb6"));
        sbxb6->setGeometry(QRect(70, 30, 42, 22));
        sbxb6->setMaximum(4096);
        sbyb6 = new QSpinBox(groupBox_15);
        sbyb6->setObjectName(QString::fromUtf8("sbyb6"));
        sbyb6->setGeometry(QRect(70, 70, 42, 22));
        sbyb6->setMaximum(4096);
        lcolorc6 = new QLabel(groupBox_15);
        lcolorc6->setObjectName(QString::fromUtf8("lcolorc6"));
        lcolorc6->setGeometry(QRect(120, 30, 21, 21));
        lcolord6 = new QLabel(groupBox_15);
        lcolord6->setObjectName(QString::fromUtf8("lcolord6"));
        lcolord6->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogc6 = new QPushButton(groupBox_15);
        pbColorDialogc6->setObjectName(QString::fromUtf8("pbColorDialogc6"));
        pbColorDialogc6->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogd6 = new QPushButton(groupBox_15);
        pbColorDialogd6->setObjectName(QString::fromUtf8("pbColorDialogd6"));
        pbColorDialogd6->setGeometry(QRect(154, 70, 91, 23));
        groupBox_16 = new QGroupBox(page_6);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(20, 10, 251, 101));
        label_33 = new QLabel(groupBox_16);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 30, 61, 21));
        label_34 = new QLabel(groupBox_16);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(10, 70, 51, 16));
        sbxa6 = new QSpinBox(groupBox_16);
        sbxa6->setObjectName(QString::fromUtf8("sbxa6"));
        sbxa6->setGeometry(QRect(70, 30, 42, 22));
        sbxa6->setMaximum(4096);
        sbya6 = new QSpinBox(groupBox_16);
        sbya6->setObjectName(QString::fromUtf8("sbya6"));
        sbya6->setGeometry(QRect(70, 70, 42, 22));
        sbya6->setMaximum(4096);
        lcolora6 = new QLabel(groupBox_16);
        lcolora6->setObjectName(QString::fromUtf8("lcolora6"));
        lcolora6->setGeometry(QRect(120, 30, 21, 21));
        lcolorb6 = new QLabel(groupBox_16);
        lcolorb6->setObjectName(QString::fromUtf8("lcolorb6"));
        lcolorb6->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoga6 = new QPushButton(groupBox_16);
        pbColorDialoga6->setObjectName(QString::fromUtf8("pbColorDialoga6"));
        pbColorDialoga6->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogb6 = new QPushButton(groupBox_16);
        pbColorDialogb6->setObjectName(QString::fromUtf8("pbColorDialogb6"));
        pbColorDialogb6->setGeometry(QRect(154, 70, 91, 23));
        groupBox_17 = new QGroupBox(page_6);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(280, 130, 251, 101));
        label_35 = new QLabel(groupBox_17);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 30, 61, 21));
        label_36 = new QLabel(groupBox_17);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(10, 70, 51, 21));
        sbxd6 = new QSpinBox(groupBox_17);
        sbxd6->setObjectName(QString::fromUtf8("sbxd6"));
        sbxd6->setGeometry(QRect(70, 30, 42, 22));
        sbxd6->setMaximum(4096);
        sbyd6 = new QSpinBox(groupBox_17);
        sbyd6->setObjectName(QString::fromUtf8("sbyd6"));
        sbyd6->setGeometry(QRect(70, 70, 42, 22));
        sbyd6->setMaximum(4096);
        lcolorg6 = new QLabel(groupBox_17);
        lcolorg6->setObjectName(QString::fromUtf8("lcolorg6"));
        lcolorg6->setGeometry(QRect(120, 30, 21, 21));
        lcolorh6 = new QLabel(groupBox_17);
        lcolorh6->setObjectName(QString::fromUtf8("lcolorh6"));
        lcolorh6->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogg6 = new QPushButton(groupBox_17);
        pbColorDialogg6->setObjectName(QString::fromUtf8("pbColorDialogg6"));
        pbColorDialogg6->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogh6 = new QPushButton(groupBox_17);
        pbColorDialogh6->setObjectName(QString::fromUtf8("pbColorDialogh6"));
        pbColorDialogh6->setGeometry(QRect(154, 70, 91, 23));
        groupBox_18 = new QGroupBox(page_6);
        groupBox_18->setObjectName(QString::fromUtf8("groupBox_18"));
        groupBox_18->setGeometry(QRect(20, 250, 251, 101));
        label_37 = new QLabel(groupBox_18);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(10, 30, 61, 16));
        label_38 = new QLabel(groupBox_18);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 70, 51, 16));
        sbxe6 = new QSpinBox(groupBox_18);
        sbxe6->setObjectName(QString::fromUtf8("sbxe6"));
        sbxe6->setGeometry(QRect(70, 30, 42, 22));
        sbxe6->setMaximum(4096);
        sbye6 = new QSpinBox(groupBox_18);
        sbye6->setObjectName(QString::fromUtf8("sbye6"));
        sbye6->setGeometry(QRect(70, 70, 42, 22));
        sbye6->setMaximum(4096);
        lcolori6 = new QLabel(groupBox_18);
        lcolori6->setObjectName(QString::fromUtf8("lcolori6"));
        lcolori6->setGeometry(QRect(120, 30, 21, 21));
        lcolorj6 = new QLabel(groupBox_18);
        lcolorj6->setObjectName(QString::fromUtf8("lcolorj6"));
        lcolorj6->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogi6 = new QPushButton(groupBox_18);
        pbColorDialogi6->setObjectName(QString::fromUtf8("pbColorDialogi6"));
        pbColorDialogi6->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogj6 = new QPushButton(groupBox_18);
        pbColorDialogj6->setObjectName(QString::fromUtf8("pbColorDialogj6"));
        pbColorDialogj6->setGeometry(QRect(154, 70, 91, 23));
        groupBox_19 = new QGroupBox(page_6);
        groupBox_19->setObjectName(QString::fromUtf8("groupBox_19"));
        groupBox_19->setGeometry(QRect(20, 130, 251, 101));
        label_39 = new QLabel(groupBox_19);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 30, 61, 21));
        label_40 = new QLabel(groupBox_19);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 70, 61, 16));
        sbxc6 = new QSpinBox(groupBox_19);
        sbxc6->setObjectName(QString::fromUtf8("sbxc6"));
        sbxc6->setGeometry(QRect(70, 30, 42, 22));
        sbxc6->setMaximum(4096);
        sbyc6 = new QSpinBox(groupBox_19);
        sbyc6->setObjectName(QString::fromUtf8("sbyc6"));
        sbyc6->setGeometry(QRect(70, 70, 42, 22));
        sbyc6->setMaximum(4096);
        lcolore6 = new QLabel(groupBox_19);
        lcolore6->setObjectName(QString::fromUtf8("lcolore6"));
        lcolore6->setGeometry(QRect(120, 30, 21, 21));
        lcolorf6 = new QLabel(groupBox_19);
        lcolorf6->setObjectName(QString::fromUtf8("lcolorf6"));
        lcolorf6->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoge6 = new QPushButton(groupBox_19);
        pbColorDialoge6->setObjectName(QString::fromUtf8("pbColorDialoge6"));
        pbColorDialoge6->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogf6 = new QPushButton(groupBox_19);
        pbColorDialogf6->setObjectName(QString::fromUtf8("pbColorDialogf6"));
        pbColorDialogf6->setGeometry(QRect(154, 70, 91, 23));
        groupBox_20 = new QGroupBox(page_6);
        groupBox_20->setObjectName(QString::fromUtf8("groupBox_20"));
        groupBox_20->setGeometry(QRect(280, 250, 251, 101));
        label_41 = new QLabel(groupBox_20);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 30, 61, 16));
        label_42 = new QLabel(groupBox_20);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(10, 70, 51, 16));
        sbxf6 = new QSpinBox(groupBox_20);
        sbxf6->setObjectName(QString::fromUtf8("sbxf6"));
        sbxf6->setGeometry(QRect(70, 30, 42, 22));
        sbxf6->setMaximum(4096);
        sbyf6 = new QSpinBox(groupBox_20);
        sbyf6->setObjectName(QString::fromUtf8("sbyf6"));
        sbyf6->setGeometry(QRect(70, 70, 42, 22));
        sbyf6->setMaximum(4096);
        lcolork6 = new QLabel(groupBox_20);
        lcolork6->setObjectName(QString::fromUtf8("lcolork6"));
        lcolork6->setGeometry(QRect(120, 30, 21, 21));
        lcolorl6 = new QLabel(groupBox_20);
        lcolorl6->setObjectName(QString::fromUtf8("lcolorl6"));
        lcolorl6->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogk6 = new QPushButton(groupBox_20);
        pbColorDialogk6->setObjectName(QString::fromUtf8("pbColorDialogk6"));
        pbColorDialogk6->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogl6 = new QPushButton(groupBox_20);
        pbColorDialogl6->setObjectName(QString::fromUtf8("pbColorDialogl6"));
        pbColorDialogl6->setGeometry(QRect(154, 70, 91, 23));
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QString::fromUtf8("page_7"));
        groupBox_21 = new QGroupBox(page_7);
        groupBox_21->setObjectName(QString::fromUtf8("groupBox_21"));
        groupBox_21->setGeometry(QRect(20, 0, 251, 101));
        label_43 = new QLabel(groupBox_21);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(10, 30, 61, 21));
        label_44 = new QLabel(groupBox_21);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 70, 51, 16));
        sbxa7 = new QSpinBox(groupBox_21);
        sbxa7->setObjectName(QString::fromUtf8("sbxa7"));
        sbxa7->setGeometry(QRect(70, 30, 42, 22));
        sbxa7->setMaximum(4096);
        sbya7 = new QSpinBox(groupBox_21);
        sbya7->setObjectName(QString::fromUtf8("sbya7"));
        sbya7->setGeometry(QRect(70, 70, 42, 22));
        sbya7->setMaximum(4096);
        lcolora7 = new QLabel(groupBox_21);
        lcolora7->setObjectName(QString::fromUtf8("lcolora7"));
        lcolora7->setGeometry(QRect(120, 30, 21, 21));
        lcolorb7 = new QLabel(groupBox_21);
        lcolorb7->setObjectName(QString::fromUtf8("lcolorb7"));
        lcolorb7->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoga7 = new QPushButton(groupBox_21);
        pbColorDialoga7->setObjectName(QString::fromUtf8("pbColorDialoga7"));
        pbColorDialoga7->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogb7 = new QPushButton(groupBox_21);
        pbColorDialogb7->setObjectName(QString::fromUtf8("pbColorDialogb7"));
        pbColorDialogb7->setGeometry(QRect(154, 70, 91, 23));
        groupBox_22 = new QGroupBox(page_7);
        groupBox_22->setObjectName(QString::fromUtf8("groupBox_22"));
        groupBox_22->setGeometry(QRect(280, 0, 251, 101));
        label_45 = new QLabel(groupBox_22);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 30, 61, 21));
        label_46 = new QLabel(groupBox_22);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(10, 70, 51, 21));
        sbxb7 = new QSpinBox(groupBox_22);
        sbxb7->setObjectName(QString::fromUtf8("sbxb7"));
        sbxb7->setGeometry(QRect(70, 30, 42, 22));
        sbxb7->setMaximum(4096);
        sbyb7 = new QSpinBox(groupBox_22);
        sbyb7->setObjectName(QString::fromUtf8("sbyb7"));
        sbyb7->setGeometry(QRect(70, 70, 42, 22));
        sbyb7->setMaximum(4096);
        lcolorc7 = new QLabel(groupBox_22);
        lcolorc7->setObjectName(QString::fromUtf8("lcolorc7"));
        lcolorc7->setGeometry(QRect(120, 30, 21, 21));
        lcolord7 = new QLabel(groupBox_22);
        lcolord7->setObjectName(QString::fromUtf8("lcolord7"));
        lcolord7->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogc7 = new QPushButton(groupBox_22);
        pbColorDialogc7->setObjectName(QString::fromUtf8("pbColorDialogc7"));
        pbColorDialogc7->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogd7 = new QPushButton(groupBox_22);
        pbColorDialogd7->setObjectName(QString::fromUtf8("pbColorDialogd7"));
        pbColorDialogd7->setGeometry(QRect(154, 70, 91, 23));
        groupBox_23 = new QGroupBox(page_7);
        groupBox_23->setObjectName(QString::fromUtf8("groupBox_23"));
        groupBox_23->setGeometry(QRect(280, 100, 251, 101));
        label_47 = new QLabel(groupBox_23);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(10, 30, 61, 21));
        label_48 = new QLabel(groupBox_23);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(10, 70, 51, 21));
        sbxd7 = new QSpinBox(groupBox_23);
        sbxd7->setObjectName(QString::fromUtf8("sbxd7"));
        sbxd7->setGeometry(QRect(70, 30, 42, 22));
        sbxd7->setMaximum(4096);
        sbyd7 = new QSpinBox(groupBox_23);
        sbyd7->setObjectName(QString::fromUtf8("sbyd7"));
        sbyd7->setGeometry(QRect(70, 70, 42, 22));
        sbyd7->setMaximum(4096);
        lcolorg7 = new QLabel(groupBox_23);
        lcolorg7->setObjectName(QString::fromUtf8("lcolorg7"));
        lcolorg7->setGeometry(QRect(120, 30, 21, 21));
        lcolorh7 = new QLabel(groupBox_23);
        lcolorh7->setObjectName(QString::fromUtf8("lcolorh7"));
        lcolorh7->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogg7 = new QPushButton(groupBox_23);
        pbColorDialogg7->setObjectName(QString::fromUtf8("pbColorDialogg7"));
        pbColorDialogg7->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogh7 = new QPushButton(groupBox_23);
        pbColorDialogh7->setObjectName(QString::fromUtf8("pbColorDialogh7"));
        pbColorDialogh7->setGeometry(QRect(154, 70, 91, 23));
        groupBox_24 = new QGroupBox(page_7);
        groupBox_24->setObjectName(QString::fromUtf8("groupBox_24"));
        groupBox_24->setGeometry(QRect(20, 200, 251, 101));
        label_49 = new QLabel(groupBox_24);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(10, 30, 61, 16));
        label_50 = new QLabel(groupBox_24);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(10, 70, 51, 16));
        sbxe7 = new QSpinBox(groupBox_24);
        sbxe7->setObjectName(QString::fromUtf8("sbxe7"));
        sbxe7->setGeometry(QRect(70, 30, 42, 22));
        sbxe7->setMaximum(4096);
        sbye7 = new QSpinBox(groupBox_24);
        sbye7->setObjectName(QString::fromUtf8("sbye7"));
        sbye7->setGeometry(QRect(70, 70, 42, 22));
        sbye7->setMaximum(4096);
        lcolori7 = new QLabel(groupBox_24);
        lcolori7->setObjectName(QString::fromUtf8("lcolori7"));
        lcolori7->setGeometry(QRect(120, 30, 21, 21));
        lcolorj7 = new QLabel(groupBox_24);
        lcolorj7->setObjectName(QString::fromUtf8("lcolorj7"));
        lcolorj7->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogi7 = new QPushButton(groupBox_24);
        pbColorDialogi7->setObjectName(QString::fromUtf8("pbColorDialogi7"));
        pbColorDialogi7->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogj7 = new QPushButton(groupBox_24);
        pbColorDialogj7->setObjectName(QString::fromUtf8("pbColorDialogj7"));
        pbColorDialogj7->setGeometry(QRect(154, 70, 91, 23));
        groupBox_25 = new QGroupBox(page_7);
        groupBox_25->setObjectName(QString::fromUtf8("groupBox_25"));
        groupBox_25->setGeometry(QRect(20, 100, 251, 101));
        label_51 = new QLabel(groupBox_25);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 30, 61, 21));
        label_52 = new QLabel(groupBox_25);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(10, 70, 61, 16));
        sbxc7 = new QSpinBox(groupBox_25);
        sbxc7->setObjectName(QString::fromUtf8("sbxc7"));
        sbxc7->setGeometry(QRect(70, 30, 42, 22));
        sbxc7->setMaximum(4096);
        sbyc7 = new QSpinBox(groupBox_25);
        sbyc7->setObjectName(QString::fromUtf8("sbyc7"));
        sbyc7->setGeometry(QRect(70, 70, 42, 22));
        sbyc7->setMaximum(4096);
        lcolore7 = new QLabel(groupBox_25);
        lcolore7->setObjectName(QString::fromUtf8("lcolore7"));
        lcolore7->setGeometry(QRect(120, 30, 21, 21));
        lcolorf7 = new QLabel(groupBox_25);
        lcolorf7->setObjectName(QString::fromUtf8("lcolorf7"));
        lcolorf7->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialoge7 = new QPushButton(groupBox_25);
        pbColorDialoge7->setObjectName(QString::fromUtf8("pbColorDialoge7"));
        pbColorDialoge7->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogf7 = new QPushButton(groupBox_25);
        pbColorDialogf7->setObjectName(QString::fromUtf8("pbColorDialogf7"));
        pbColorDialogf7->setGeometry(QRect(154, 70, 91, 23));
        groupBox_26 = new QGroupBox(page_7);
        groupBox_26->setObjectName(QString::fromUtf8("groupBox_26"));
        groupBox_26->setGeometry(QRect(280, 200, 251, 101));
        label_53 = new QLabel(groupBox_26);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(10, 30, 61, 16));
        label_54 = new QLabel(groupBox_26);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(10, 70, 51, 16));
        sbxf7 = new QSpinBox(groupBox_26);
        sbxf7->setObjectName(QString::fromUtf8("sbxf7"));
        sbxf7->setGeometry(QRect(70, 30, 42, 22));
        sbxf7->setMaximum(4096);
        sbyf7 = new QSpinBox(groupBox_26);
        sbyf7->setObjectName(QString::fromUtf8("sbyf7"));
        sbyf7->setGeometry(QRect(70, 70, 42, 22));
        sbyf7->setMaximum(4096);
        lcolork7 = new QLabel(groupBox_26);
        lcolork7->setObjectName(QString::fromUtf8("lcolork7"));
        lcolork7->setGeometry(QRect(120, 30, 21, 21));
        lcolorl7 = new QLabel(groupBox_26);
        lcolorl7->setObjectName(QString::fromUtf8("lcolorl7"));
        lcolorl7->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogk7 = new QPushButton(groupBox_26);
        pbColorDialogk7->setObjectName(QString::fromUtf8("pbColorDialogk7"));
        pbColorDialogk7->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogl7 = new QPushButton(groupBox_26);
        pbColorDialogl7->setObjectName(QString::fromUtf8("pbColorDialogl7"));
        pbColorDialogl7->setGeometry(QRect(154, 70, 91, 23));
        groupBox_27 = new QGroupBox(page_7);
        groupBox_27->setObjectName(QString::fromUtf8("groupBox_27"));
        groupBox_27->setGeometry(QRect(150, 300, 251, 101));
        label_55 = new QLabel(groupBox_27);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 30, 61, 16));
        label_56 = new QLabel(groupBox_27);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(10, 70, 51, 16));
        sbxg7 = new QSpinBox(groupBox_27);
        sbxg7->setObjectName(QString::fromUtf8("sbxg7"));
        sbxg7->setGeometry(QRect(70, 30, 42, 22));
        sbxg7->setMaximum(4096);
        sbyg7 = new QSpinBox(groupBox_27);
        sbyg7->setObjectName(QString::fromUtf8("sbyg7"));
        sbyg7->setGeometry(QRect(70, 70, 42, 22));
        sbyg7->setMaximum(4096);
        lcolorm7 = new QLabel(groupBox_27);
        lcolorm7->setObjectName(QString::fromUtf8("lcolorm7"));
        lcolorm7->setGeometry(QRect(120, 30, 21, 21));
        lcolorn7 = new QLabel(groupBox_27);
        lcolorn7->setObjectName(QString::fromUtf8("lcolorn7"));
        lcolorn7->setGeometry(QRect(120, 70, 21, 21));
        pbColorDialogm7 = new QPushButton(groupBox_27);
        pbColorDialogm7->setObjectName(QString::fromUtf8("pbColorDialogm7"));
        pbColorDialogm7->setGeometry(QRect(154, 30, 91, 23));
        pbColorDialogn7 = new QPushButton(groupBox_27);
        pbColorDialogn7->setObjectName(QString::fromUtf8("pbColorDialogn7"));
        pbColorDialogn7->setGeometry(QRect(154, 70, 91, 23));
        stackedWidget->addWidget(page_7);

        gridLayout_2->addWidget(stackedWidget, 1, 0, 1, 3);

        pbCancel = new QPushButton(RGBSegment);
        pbCancel->setObjectName(QString::fromUtf8("pbCancel"));

        gridLayout_2->addWidget(pbCancel, 2, 2, 1, 1);

        pbAccept = new QPushButton(RGBSegment);
        pbAccept->setObjectName(QString::fromUtf8("pbAccept"));

        gridLayout_2->addWidget(pbAccept, 2, 1, 1, 1);

        QWidget::setTabOrder(comboBox, sbx);
        QWidget::setTabOrder(sbx, pbColorDialogx);
        QWidget::setTabOrder(pbColorDialogx, sby);
        QWidget::setTabOrder(sby, pbColorDialogy);
        QWidget::setTabOrder(pbColorDialogy, sbxa2);
        QWidget::setTabOrder(sbxa2, pbColorDialogxa);
        QWidget::setTabOrder(pbColorDialogxa, sbya2);
        QWidget::setTabOrder(sbya2, pbColorDialogya);
        QWidget::setTabOrder(pbColorDialogya, sbxb2);
        QWidget::setTabOrder(sbxb2, pbColorDialogxb);
        QWidget::setTabOrder(pbColorDialogxb, sbyb2);
        QWidget::setTabOrder(sbyb2, pbColorDialogyb);
        QWidget::setTabOrder(pbColorDialogyb, sbxa3);
        QWidget::setTabOrder(sbxa3, pbColorDialoga3);
        QWidget::setTabOrder(pbColorDialoga3, sbya3);
        QWidget::setTabOrder(sbya3, pbColorDialogb3);
        QWidget::setTabOrder(pbColorDialogb3, sbxb3);
        QWidget::setTabOrder(sbxb3, pbColorDialogc3);
        QWidget::setTabOrder(pbColorDialogc3, sbyb3);
        QWidget::setTabOrder(sbyb3, pbColorDialogd3);
        QWidget::setTabOrder(pbColorDialogd3, sbxc3);
        QWidget::setTabOrder(sbxc3, pbColorDialoge3);
        QWidget::setTabOrder(pbColorDialoge3, sbyc3);
        QWidget::setTabOrder(sbyc3, pbColorDialogf3);
        QWidget::setTabOrder(pbColorDialogf3, sbxa4);
        QWidget::setTabOrder(sbxa4, pbColorDialoga4);
        QWidget::setTabOrder(pbColorDialoga4, sbya4);
        QWidget::setTabOrder(sbya4, pbColorDialogb4);
        QWidget::setTabOrder(pbColorDialogb4, sbxb4);
        QWidget::setTabOrder(sbxb4, pbColorDialogc4);
        QWidget::setTabOrder(pbColorDialogc4, sbyb4);
        QWidget::setTabOrder(sbyb4, pbColorDialogd4);
        QWidget::setTabOrder(pbColorDialogd4, sbxc4);
        QWidget::setTabOrder(sbxc4, pbColorDialoge4);
        QWidget::setTabOrder(pbColorDialoge4, sbyc4);
        QWidget::setTabOrder(sbyc4, pbColorDialogf4);
        QWidget::setTabOrder(pbColorDialogf4, sbxd4);
        QWidget::setTabOrder(sbxd4, pbColorDialogg4);
        QWidget::setTabOrder(pbColorDialogg4, sbyd4);
        QWidget::setTabOrder(sbyd4, pbColorDialogh4);
        QWidget::setTabOrder(pbColorDialogh4, sbxa5);
        QWidget::setTabOrder(sbxa5, pbColorDialoga5);
        QWidget::setTabOrder(pbColorDialoga5, sbya5);
        QWidget::setTabOrder(sbya5, pbColorDialogb5);
        QWidget::setTabOrder(pbColorDialogb5, sbxb5);
        QWidget::setTabOrder(sbxb5, pbColorDialogc5);
        QWidget::setTabOrder(pbColorDialogc5, sbyb5);
        QWidget::setTabOrder(sbyb5, pbColorDialogd5);
        QWidget::setTabOrder(pbColorDialogd5, sbxc5);
        QWidget::setTabOrder(sbxc5, pbColorDialoge5);
        QWidget::setTabOrder(pbColorDialoge5, sbyc5);
        QWidget::setTabOrder(sbyc5, pbColorDialogf5);
        QWidget::setTabOrder(pbColorDialogf5, sbxd5);
        QWidget::setTabOrder(sbxd5, pbColorDialogg5);
        QWidget::setTabOrder(pbColorDialogg5, sbyd5);
        QWidget::setTabOrder(sbyd5, pbColorDialogh5);
        QWidget::setTabOrder(pbColorDialogh5, sbxe5);
        QWidget::setTabOrder(sbxe5, pbColorDialogi5);
        QWidget::setTabOrder(pbColorDialogi5, sbye5);
        QWidget::setTabOrder(sbye5, pbColorDialogj5);
        QWidget::setTabOrder(pbColorDialogj5, sbxa6);
        QWidget::setTabOrder(sbxa6, pbColorDialoga6);
        QWidget::setTabOrder(pbColorDialoga6, sbya6);
        QWidget::setTabOrder(sbya6, pbColorDialogb6);
        QWidget::setTabOrder(pbColorDialogb6, sbxb6);
        QWidget::setTabOrder(sbxb6, pbColorDialogc6);
        QWidget::setTabOrder(pbColorDialogc6, sbyb6);
        QWidget::setTabOrder(sbyb6, pbColorDialogd6);
        QWidget::setTabOrder(pbColorDialogd6, sbxc6);
        QWidget::setTabOrder(sbxc6, pbColorDialoge6);
        QWidget::setTabOrder(pbColorDialoge6, sbyc6);
        QWidget::setTabOrder(sbyc6, pbColorDialogf6);
        QWidget::setTabOrder(pbColorDialogf6, sbxd6);
        QWidget::setTabOrder(sbxd6, pbColorDialogg6);
        QWidget::setTabOrder(pbColorDialogg6, sbyd6);
        QWidget::setTabOrder(sbyd6, pbColorDialogh6);
        QWidget::setTabOrder(pbColorDialogh6, sbxe6);
        QWidget::setTabOrder(sbxe6, pbColorDialogi6);
        QWidget::setTabOrder(pbColorDialogi6, sbye6);
        QWidget::setTabOrder(sbye6, pbColorDialogj6);
        QWidget::setTabOrder(pbColorDialogj6, sbxf6);
        QWidget::setTabOrder(sbxf6, pbColorDialogk6);
        QWidget::setTabOrder(pbColorDialogk6, sbyf6);
        QWidget::setTabOrder(sbyf6, pbColorDialogl6);
        QWidget::setTabOrder(pbColorDialogl6, sbxa7);
        QWidget::setTabOrder(sbxa7, pbColorDialoga7);
        QWidget::setTabOrder(pbColorDialoga7, sbya7);
        QWidget::setTabOrder(sbya7, pbColorDialogb7);
        QWidget::setTabOrder(pbColorDialogb7, sbxb7);
        QWidget::setTabOrder(sbxb7, pbColorDialogc7);
        QWidget::setTabOrder(pbColorDialogc7, sbyb7);
        QWidget::setTabOrder(sbyb7, pbColorDialogd7);
        QWidget::setTabOrder(pbColorDialogd7, sbxc7);
        QWidget::setTabOrder(sbxc7, pbColorDialoge7);
        QWidget::setTabOrder(pbColorDialoge7, sbyc7);
        QWidget::setTabOrder(sbyc7, pbColorDialogf7);
        QWidget::setTabOrder(pbColorDialogf7, sbxd7);
        QWidget::setTabOrder(sbxd7, pbColorDialogg7);
        QWidget::setTabOrder(pbColorDialogg7, sbyd7);
        QWidget::setTabOrder(sbyd7, pbColorDialogh7);
        QWidget::setTabOrder(pbColorDialogh7, sbxe7);
        QWidget::setTabOrder(sbxe7, pbColorDialogi7);
        QWidget::setTabOrder(pbColorDialogi7, sbye7);
        QWidget::setTabOrder(sbye7, pbColorDialogj7);
        QWidget::setTabOrder(pbColorDialogj7, sbxf7);
        QWidget::setTabOrder(sbxf7, pbColorDialogk7);
        QWidget::setTabOrder(pbColorDialogk7, sbyf7);
        QWidget::setTabOrder(sbyf7, pbColorDialogl7);
        QWidget::setTabOrder(pbColorDialogl7, sbxg7);
        QWidget::setTabOrder(sbxg7, pbColorDialogm7);
        QWidget::setTabOrder(pbColorDialogm7, sbyg7);
        QWidget::setTabOrder(sbyg7, pbColorDialogn7);

        retranslateUi(RGBSegment);
        QObject::connect(comboBox, SIGNAL(currentIndexChanged(int)), stackedWidget, SLOT(setCurrentIndex(int)));
        QObject::connect(pbCancel, SIGNAL(clicked()), RGBSegment, SLOT(close()));

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(RGBSegment);
    } // setupUi

    void retranslateUi(QWidget *RGBSegment)
    {
        RGBSegment->setWindowTitle(QApplication::translate("RGBSegment", "Segmentos de color", 0, QApplication::UnicodeUTF8));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("RGBSegment", "Un Solo Segmento", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("RGBSegment", "Dos Segmentos", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("RGBSegment", "Tres Segmentos", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("RGBSegment", "Cuatro segmentos", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("RGBSegment", "Cinco Segmentos", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("RGBSegment", "Seis Segmentos", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("RGBSegment", "Siete Segmentos", 0, QApplication::UnicodeUTF8)
        );
        label->setText(QApplication::translate("RGBSegment", "Valor inicial: ", 0, QApplication::UnicodeUTF8));
        lcolorx->setText(QString());
        pbColorDialogx->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("RGBSegment", "Valor final: ", 0, QApplication::UnicodeUTF8));
        lcolory->setText(QString());
        pbColorDialogy->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("RGBSegment", "Segmento A", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolora2->setText(QString());
        lcolorb2->setText(QString());
        pbColorDialogxa->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogya->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("RGBSegment", "Segmento B", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        lcolorc2->setText(QString());
        pbColorDialogxb->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolord2->setText(QString());
        pbColorDialogyb->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("RGBSegment", "Segmento A", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolora3->setText(QString());
        lcolorb3->setText(QString());
        pbColorDialoga3->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogb3->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("RGBSegment", "Segmento B", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorc3->setText(QString());
        lcolord3->setText(QString());
        pbColorDialogc3->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogd3->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("RGBSegment", "Segmento C", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolore3->setText(QString());
        lcolorf3->setText(QString());
        pbColorDialoge3->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogf3->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("RGBSegment", "Segmento A", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("RGBSegment", "Valor final: ", 0, QApplication::UnicodeUTF8));
        lcolora4->setText(QString());
        lcolorb4->setText(QString());
        pbColorDialoga4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogb4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QApplication::translate("RGBSegment", "Segmento B", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorc4->setText(QString());
        lcolord4->setText(QString());
        pbColorDialogc4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogd4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("RGBSegment", "Segmento C", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolore4->setText(QString());
        lcolorf4->setText(QString());
        pbColorDialoge4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogf4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_9->setTitle(QApplication::translate("RGBSegment", "Segmento D", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorg4->setText(QString());
        lcolorh4->setText(QString());
        pbColorDialogg4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        pbColorDialogh4->setText(QApplication::translate("RGBSegment", "Seleccione color", 0, QApplication::UnicodeUTF8));
        groupBox_10->setTitle(QApplication::translate("RGBSegment", "Segmento A", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolora5->setText(QString());
        lcolorb5->setText(QString());
        pbColorDialoga5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogb5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_11->setTitle(QApplication::translate("RGBSegment", "Segmento B", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorc5->setText(QString());
        lcolord5->setText(QString());
        pbColorDialogc5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogd5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_12->setTitle(QApplication::translate("RGBSegment", "Segmento C", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolore5->setText(QString());
        lcolorf5->setText(QString());
        pbColorDialoge5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogf5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_13->setTitle(QApplication::translate("RGBSegment", "Segmento D", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorg5->setText(QString());
        lcolorh5->setText(QString());
        pbColorDialogg5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogh5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_14->setTitle(QApplication::translate("RGBSegment", "Segmento E", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolori5->setText(QString());
        lcolorj5->setText(QString());
        pbColorDialogi5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogj5->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_15->setTitle(QApplication::translate("RGBSegment", "Segmento B", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorc6->setText(QString());
        lcolord6->setText(QString());
        pbColorDialogc6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogd6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_16->setTitle(QApplication::translate("RGBSegment", "Segmento A", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolora6->setText(QString());
        lcolorb6->setText(QString());
        pbColorDialoga6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogb6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_17->setTitle(QApplication::translate("RGBSegment", "Segmento D", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorg6->setText(QString());
        lcolorh6->setText(QString());
        pbColorDialogg6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogh6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_18->setTitle(QApplication::translate("RGBSegment", "Segmento E", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolori6->setText(QString());
        lcolorj6->setText(QString());
        pbColorDialogi6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogj6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_19->setTitle(QApplication::translate("RGBSegment", "Segmento C", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolore6->setText(QString());
        lcolorf6->setText(QString());
        pbColorDialoge6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogf6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_20->setTitle(QApplication::translate("RGBSegment", "Segmento F", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolork6->setText(QString());
        lcolorl6->setText(QString());
        pbColorDialogk6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogl6->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_21->setTitle(QApplication::translate("RGBSegment", "Segmento A", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolora7->setText(QString());
        lcolorb7->setText(QString());
        pbColorDialoga7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogb7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_22->setTitle(QApplication::translate("RGBSegment", "Segmento B", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorc7->setText(QString());
        lcolord7->setText(QString());
        pbColorDialogc7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogd7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_23->setTitle(QApplication::translate("RGBSegment", "Segmento D", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorg7->setText(QString());
        lcolorh7->setText(QString());
        pbColorDialogg7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogh7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_24->setTitle(QApplication::translate("RGBSegment", "Segmento E", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolori7->setText(QString());
        lcolorj7->setText(QString());
        pbColorDialogi7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogj7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_25->setTitle(QApplication::translate("RGBSegment", "Segmento C", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolore7->setText(QString());
        lcolorf7->setText(QString());
        pbColorDialoge7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogf7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_26->setTitle(QApplication::translate("RGBSegment", "Segmento F", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolork7->setText(QString());
        lcolorl7->setText(QString());
        pbColorDialogk7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogl7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        groupBox_27->setTitle(QApplication::translate("RGBSegment", "Segmento G", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("RGBSegment", "Valor inicial:", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("RGBSegment", "Valor final:", 0, QApplication::UnicodeUTF8));
        lcolorm7->setText(QString());
        lcolorn7->setText(QString());
        pbColorDialogm7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbColorDialogn7->setText(QApplication::translate("RGBSegment", "Selecciona color", 0, QApplication::UnicodeUTF8));
        pbCancel->setText(QApplication::translate("RGBSegment", "Cancelar", 0, QApplication::UnicodeUTF8));
        pbAccept->setText(QApplication::translate("RGBSegment", "Aceptar", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class RGBSegment: public Ui_RGBSegment {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_RGBSEGMENT_H
